/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package picturematching.views;

import javax.swing.ImageIcon;
import picturematching.Main;
import picturematching.models.User;

/**
 *
 * @author Ramdan Rohendi
 */
public class Profile extends javax.swing.JFrame {

    public Profile() {
        initComponents();
        
        String dirIconProfile = "/picturematching/assets/profile/"+Main.userlogin.getIcon_profile();
        ImageIcon gbrIconProfile = new ImageIcon(getClass().getResource(dirIconProfile));
        txtIcon.setIcon(gbrIconProfile);
        txtNamaLengkap.setText(Main.userlogin.getNama_lengkap());
        txtUsername.setText(Main.userlogin.getUsername());
        txtTglLahir.setText(Main.userlogin.getTanggal_lahir() == null ? "~" : Main.userlogin.getTanggal_lahir().toString());
        txtTentangSaya.setText(Main.userlogin.getTentang_saya());
        
        txtBestScore.setText(Main.userlogin.myHistory().getBest_score() + "");
        txtJmlPlayNormal.setText(Main.userlogin.myHistory().getJml_play_normal() + "");
        txtJmlPlayHard.setText(Main.userlogin.myHistory().getJml_play_hard() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        btnHighscore = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnStart = new javax.swing.JLabel();
        pnlIdentitas = new javax.swing.JPanel();
        txtIcon = new javax.swing.JLabel();
        txtNamaLengkap = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtTglLahir = new javax.swing.JLabel();
        pnlTentang = new javax.swing.JPanel();
        scrPaneTentangSaya = new javax.swing.JScrollPane();
        txtTentangSaya = new javax.swing.JTextArea();
        pnlHistory = new javax.swing.JPanel();
        lblBestScore = new javax.swing.JLabel();
        lblJmlPlayNormal = new javax.swing.JLabel();
        lblJmlPlayHard = new javax.swing.JLabel();
        txtBestScore = new javax.swing.JLabel();
        txtJmlPlayNormal = new javax.swing.JLabel();
        txtJmlPlayHard = new javax.swing.JLabel();
        Foot = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Picture Matching - Profile");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Head.setBackground(new java.awt.Color(102, 102, 102));

        btnHighscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picturematching/assets/ranking.png"))); // NOI18N
        btnHighscore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHighscore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHighscoreMouseClicked(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picturematching/assets/logout.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picturematching/assets/edit.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHighscore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(btnLogout)
                    .addComponent(btnHighscore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Body.setBackground(new java.awt.Color(204, 204, 204));

        Title.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("My Profile");

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picturematching/assets/btnexport.png"))); // NOI18N
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        txtIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picturematching/assets/profile/burunghantu.png"))); // NOI18N

        txtNamaLengkap.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNamaLengkap.setText("Player One");

        txtUsername.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        txtUsername.setText("player1");

        txtTglLahir.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        txtTglLahir.setText("19 November 2002");

        javax.swing.GroupLayout pnlIdentitasLayout = new javax.swing.GroupLayout(pnlIdentitas);
        pnlIdentitas.setLayout(pnlIdentitasLayout);
        pnlIdentitasLayout.setHorizontalGroup(
            pnlIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdentitasLayout.createSequentialGroup()
                        .addComponent(txtNamaLengkap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(txtTglLahir))
                    .addGroup(pnlIdentitasLayout.createSequentialGroup()
                        .addComponent(txtUsername)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlIdentitasLayout.setVerticalGroup(
            pnlIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIcon)
                    .addGroup(pnlIdentitasLayout.createSequentialGroup()
                        .addGroup(pnlIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIdentitasLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtNamaLengkap))
                            .addComponent(txtTglLahir))
                        .addGap(3, 3, 3)
                        .addComponent(txtUsername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrPaneTentangSaya.setBackground(new java.awt.Color(242, 242, 242));

        txtTentangSaya.setEditable(false);
        txtTentangSaya.setColumns(20);
        txtTentangSaya.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtTentangSaya.setLineWrap(true);
        txtTentangSaya.setRows(5);
        txtTentangSaya.setText("Tentang saya...");
        scrPaneTentangSaya.setViewportView(txtTentangSaya);

        javax.swing.GroupLayout pnlTentangLayout = new javax.swing.GroupLayout(pnlTentang);
        pnlTentang.setLayout(pnlTentangLayout);
        pnlTentangLayout.setHorizontalGroup(
            pnlTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPaneTentangSaya)
                .addContainerGap())
        );
        pnlTentangLayout.setVerticalGroup(
            pnlTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPaneTentangSaya, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblBestScore.setText("Best Score : ");

        lblJmlPlayNormal.setText("Jumlah Permainan Normal : ");

        lblJmlPlayHard.setText("Jumlah Permainan Hard : ");

        txtBestScore.setText("10000");

        txtJmlPlayNormal.setText("15");

        txtJmlPlayHard.setText("20");

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblBestScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBestScore))
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblJmlPlayNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJmlPlayNormal))
                    .addGroup(pnlHistoryLayout.createSequentialGroup()
                        .addComponent(lblJmlPlayHard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJmlPlayHard)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBestScore)
                    .addComponent(txtBestScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJmlPlayNormal)
                    .addComponent(txtJmlPlayNormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJmlPlayHard)
                    .addComponent(txtJmlPlayHard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlIdentitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTentang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(pnlIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap())
        );

        Foot.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout FootLayout = new javax.swing.GroupLayout(Foot);
        Foot.setLayout(FootLayout);
        FootLayout.setHorizontalGroup(
            FootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FootLayout.setVerticalGroup(
            FootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Foot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Foot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        SelectDifficulty viewDifficulty = new SelectDifficulty();
        viewDifficulty.setLocation(this.getLocation());
        viewDifficulty.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStartMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Home home = new Home();
        home.setLocation(this.getLocation());
        home.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnHighscoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighscoreMouseClicked
        Highscore highscore = new Highscore();
        highscore.setLocation(this.getLocation());
        highscore.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHighscoreMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        EditProfile editProfile = new EditProfile();
        editProfile.setLocation(this.getLocation());
        editProfile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        Main.is_login = false;
        Main.userlogin = new User();
        
        Home home = new Home();
        home.setLocation(this.getLocation());
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Foot;
    private javax.swing.JPanel Head;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel btnHighscore;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnStart;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblBestScore;
    private javax.swing.JLabel lblJmlPlayHard;
    private javax.swing.JLabel lblJmlPlayNormal;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlIdentitas;
    private javax.swing.JPanel pnlTentang;
    private javax.swing.JScrollPane scrPaneTentangSaya;
    private javax.swing.JLabel txtBestScore;
    private javax.swing.JLabel txtIcon;
    private javax.swing.JLabel txtJmlPlayHard;
    private javax.swing.JLabel txtJmlPlayNormal;
    private javax.swing.JLabel txtNamaLengkap;
    private javax.swing.JTextArea txtTentangSaya;
    private javax.swing.JLabel txtTglLahir;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
